site_name: Deep Java Client Docs
site_url: https://intergral.github.io/deep-java-client

repo_name: Deep Java Client
repo_url: https://github.com/intergral/deep-java-client

copyright: Intergral GmbH 2023

theme:
  logo: https://github.com/intergral/deep/blob/master/docs/docs/images/logo/icon.png?raw=true
  favicon: https://github.com/intergral/deep/blob/master/docs/docs/images/logo/icon.svg?raw=true
  name: material
  features:
    - content.code.copy

extra_css:
  - styles/styles.css

nav:
  - Home: index.md
  - Config: config/config.md
  - Auth:
      - Providers: auth/providers.md
  - Maven Site & Java Docs: https://intergral.github.io/deep-java-client/mvn/index.html

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
