site_name: Deep Java Client Docs
site_url: https://intergral.github.io/deep-java-client

repo_name: Deep Java Client
repo_url: https://github.com/intergral/deep-java-client

copyright: Intergral GmbH 2023

theme:
  name: material

nav:
  - Home: index.md
  - Config: config/config.md
  - Auth:
      - Providers: auth/providers.md
  - Maven Site & Java Docs: https://intergral.github.io/deep-java-client/mvn/index.html
