name: CF IT Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cfTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "${{ github.event_name }}"
          NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)
          echo "$NEW_COMMIT_COUNT"
          echo "CHANGE_COUNT=$NEW_COMMIT_COUNT" >> $GITHUB_OUTPUT
          echo $({{ github.event.event_name }} == 'workflow_dispatch' || ${NEW_COMMIT_COUNT} > 0)

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        if: ${{ github.event.event_name == 'workflow_dispatch' || env.CHANGE_COUNT > 0 }}
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run CF Tests
        if: ${{ github.event.event_name == 'workflow_dispatch' || env.CHANGE_COUNT > 0 }}
        run: make cf-tests