name: CF IT Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cfTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo {{ github.event_name }}
          NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)
          echo "$NEW_COMMIT_COUNT"
          echo "SHOULD_BUILD=${{ env.MY_VAR }}" >> $GITHUB_OUTPUT

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run CF Tests
        run: make cf-tests