name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
      OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      VERSION: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Update java version
        run: mvn versions:set -DnewVersion=${VERSION} -B -U
      - name: Build and Release
        run: mvn -s .ci-settings.xml clean deploy -P release-ossrh -B -U -pl agent --also-make