name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
      OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      VERSION: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Update java version
        run: mvn versions:set -DnewVersion=${VERSION} -B -U
      - name: Build and Release
        run: mvn -s .ci-settings.xml clean deploy -DskipTests -P release-ossrh -B -U -pl agent,deep --also-make

      - name: Upload agent to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./agent/target/agent-${VERSION}.jar
          asset_name: Deep Agent
          tag: ${{ github.ref_name }}
          overwrite: true

      - name: Upload lite agent to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./agent/target/agent-${VERSION}-lite.jar
          asset_name: Deep Lite Agent
          tag: ${{ github.ref_name }}
          overwrite: true

  JavaSite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Update java version
        run: mvn versions:set -DnewVersion=${VERSION} -B -U

      - name: Package project
        run: mvn clean package -DskipTests -U -B -P cf-it-tests,examples

      - name: Build site
        run: mvn -U -B site:site site:stage -P docs,cf-it-tests,examples

      - name: Zip Site
        run: tar -czf site.tar.gz target/staging

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: site.tar.gz
          asset_name: Maven Site
          tag: ${{ github.ref_name }}
          overwrite: true

