name: Deploy Pages

on:
  push:
    branches: [ "master" ]


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs build -d./_site
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mk docs
          path: _site

  mergeBuilds:
    runs-on: ubuntu-latest
    needs:
      - mkdocs
    steps:
      - name: Download Mkdocs artifact
        uses: actions/download-artifact@v4
        with:
          name: Mk docs
          path: _site

      - name: Download mvn site from latest
        uses: robinraju/release-downloader@v1.11
        with:
          latest: true
          fileName: Maven.Site

      - name: Unpack
        run: |
          mkdir -p _site/mvn 
          tar -xvf Maven.Site --strip-components=2 -C _site/mvn

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: mergeBuilds
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
